var angular = angular || {};

var app = angular.module('testApp', [ 'gawebtoolkit.core', 'gawebtoolkit.mapservices', 'gawebtoolkit.config', 'gawebtoolkit.ui' ]);

app.controller('testConfigController', [ '$scope', function($scope) {
   'use strict';

   /*$scope.$on('configDataLoaded', function (event, args) {
       $scope.gaConfig = args;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if(args.configuredGroups[i].id === $scope.groupId) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                $scope.currentGroup = args.configuredGroups[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }*//*
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        $scope.configReady = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });*/

} ]);
